from __future__ import annotations

import re
import zipfile
from xml.etree import ElementTree as ET

from schema_parser.models import SourceTable
from schema_parser.sources.base import MAX_SOURCE_BYTES, local_name


class DocxReader:
    """Reads tables from the Office Open XML body of a .docx file."""

    def can_read(self, path: str) -> bool:
        return path.lower().endswith(".docx")

    def read(self, path: str) -> list[SourceTable]:
        return _extract_docx_tables(path)


def _extract_docx_tables(path: str) -> list[SourceTable]:
    try:
        with zipfile.ZipFile(path) as archive:
            try:
                document_xml = archive.getinfo("word/document.xml")
            except KeyError as exc:
                raise ValueError(f"{path} is missing word/document.xml") from exc

            if document_xml.file_size > MAX_SOURCE_BYTES:
                raise ValueError("DOCX word/document.xml exceeds the maximum supported size.")

            xml = archive.read(document_xml)
    except zipfile.BadZipFile as exc:
        raise ValueError(
            f"{path} is not a valid ZIP-based DOCX file. "
            "Please provide a real .docx generated by Microsoft Word or save the document as .docx before retrying."
        ) from exc

    if re.search(br"<!\s*(doctype|entity)\b", xml, flags=re.IGNORECASE):
        raise ValueError("DOCX word/document.xml contains disallowed XML declarations.")

    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    root = ET.fromstring(xml)
    body = root.find(".//w:body", ns)
    if body is None:
        return []

    tables: list[SourceTable] = []
    pending_name: str | None = None

    for child in body:
        tag = local_name(child.tag)

        if tag == "p":
            text = "".join(node.text for node in child.findall(".//w:t", ns) if node.text).strip()
            if text and _looks_like_table_name(child, text, ns):
                pending_name = text
            continue

        if tag != "tbl":
            continue

        rows: list[list[str]] = []
        for row in child.findall("./w:tr", ns):
            cells: list[str] = []
            for cell in row.findall("./w:tc", ns):
                text = "".join(node.text for node in cell.findall(".//w:t", ns) if node.text).strip()
                cells.append(text)
            if any(cells):
                rows.append(cells)

        if not rows:
            continue

        name = pending_name or f"table_{len(tables) + 1}"
        headers = rows[0]
        table_rows = rows[1:]
        tables.append(SourceTable(name=name, headers=headers, rows=table_rows))
        pending_name = None

    return tables


def _looks_like_table_name(paragraph: ET.Element, text: str, ns: dict[str, str]) -> bool:
    style_el = paragraph.find("w:pPr/w:pStyle", ns)
    style = (style_el.get(f"{{{ns['w']}}}val", "") if style_el is not None else "") or ""
    if any(marker in style.lower() for marker in ("heading", "title", "caption")):
        return True
    # Fall back for unstyled captions: accept only short, heading-like lines and
    # reject prose sentences or "Label: value" lines (e.g. "Used by: ...",
    # "Routes to: Outflow Worker as a hard constraint.") so descriptive body text
    # is never mistaken for a table name.
    if len(text) > 48 or len(text.split()) > 6:
        return False
    if text[-1] in ".!?:;,":
        return False
    if ": " in text:
        return False
    return True
